# Generated by Django 3.2.18 on 2023-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
